language: node_js
node_js:
  - 10.16.2
  - 10.16.3
addons:
  chrome: stable
jobs:
  include:
    - stage: test
      script:
        - npx serve -n -l 5000 example/public &
        - SERVER_PID=$!
        - npm run test
        - kill $SERVER_PID
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: 'true'
        script:
          - npx xsemantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
